version: "3"

volumes:
  npm-cache:
    driver: local
  postgres_socket:
    driver: local

services:
  dbpostgres:
    image: postgres
    volumes:
      - ./initdb.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_socket:/var/run/postgresql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "1234"
      POSTGRES_DB: "weather"
  backend:
    image: weather-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    working_dir: /app
    environment:
      - NODE_ENV=development
    volumes:
      - ./backend:/app
      - npm-cache:/root/.npm
    ports:
      - "8090:8090"
    hostname: "localhost"
    command: "npm run dev"
    depends_on:
      - dbpostgres